name: My CICD Pipeline in GitHub Actions

on:
 push:
  branches: main
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
       
      - name: initialize Repo
        run: |
            echo "this is devops"
             uname -a

      - name: check th edocker installation
        run: |
          docker
            docker images
         

      - name: Run docker container
        run: |
          docker run hello-world
  
